package com.senchuuhi.iweb.auto.entity;

import java.util.Date;

public class AxeArticle {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column axe_article.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column axe_article.article_name
     *
     * @mbg.generated
     */
    private String articleName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column axe_article.article_author
     *
     * @mbg.generated
     */
    private String articleAuthor;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column axe_article.article_content
     *
     * @mbg.generated
     */
    private String articleContent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column axe_article.article_source
     *
     * @mbg.generated
     */
    private String articleSource;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column axe_article.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column axe_article.creator
     *
     * @mbg.generated
     */
    private String creator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column axe_article.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column axe_article.updater
     *
     * @mbg.generated
     */
    private String updater;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column axe_article.delete_flag
     *
     * @mbg.generated
     */
    private Short deleteFlag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column axe_article.id
     *
     * @return the value of axe_article.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column axe_article.id
     *
     * @param id the value for axe_article.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column axe_article.article_name
     *
     * @return the value of axe_article.article_name
     *
     * @mbg.generated
     */
    public String getArticleName() {
        return articleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column axe_article.article_name
     *
     * @param articleName the value for axe_article.article_name
     *
     * @mbg.generated
     */
    public void setArticleName(String articleName) {
        this.articleName = articleName == null ? null : articleName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column axe_article.article_author
     *
     * @return the value of axe_article.article_author
     *
     * @mbg.generated
     */
    public String getArticleAuthor() {
        return articleAuthor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column axe_article.article_author
     *
     * @param articleAuthor the value for axe_article.article_author
     *
     * @mbg.generated
     */
    public void setArticleAuthor(String articleAuthor) {
        this.articleAuthor = articleAuthor == null ? null : articleAuthor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column axe_article.article_content
     *
     * @return the value of axe_article.article_content
     *
     * @mbg.generated
     */
    public String getArticleContent() {
        return articleContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column axe_article.article_content
     *
     * @param articleContent the value for axe_article.article_content
     *
     * @mbg.generated
     */
    public void setArticleContent(String articleContent) {
        this.articleContent = articleContent == null ? null : articleContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column axe_article.article_source
     *
     * @return the value of axe_article.article_source
     *
     * @mbg.generated
     */
    public String getArticleSource() {
        return articleSource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column axe_article.article_source
     *
     * @param articleSource the value for axe_article.article_source
     *
     * @mbg.generated
     */
    public void setArticleSource(String articleSource) {
        this.articleSource = articleSource == null ? null : articleSource.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column axe_article.create_time
     *
     * @return the value of axe_article.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column axe_article.create_time
     *
     * @param createTime the value for axe_article.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column axe_article.creator
     *
     * @return the value of axe_article.creator
     *
     * @mbg.generated
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column axe_article.creator
     *
     * @param creator the value for axe_article.creator
     *
     * @mbg.generated
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column axe_article.update_time
     *
     * @return the value of axe_article.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column axe_article.update_time
     *
     * @param updateTime the value for axe_article.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column axe_article.updater
     *
     * @return the value of axe_article.updater
     *
     * @mbg.generated
     */
    public String getUpdater() {
        return updater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column axe_article.updater
     *
     * @param updater the value for axe_article.updater
     *
     * @mbg.generated
     */
    public void setUpdater(String updater) {
        this.updater = updater == null ? null : updater.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column axe_article.delete_flag
     *
     * @return the value of axe_article.delete_flag
     *
     * @mbg.generated
     */
    public Short getDeleteFlag() {
        return deleteFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column axe_article.delete_flag
     *
     * @param deleteFlag the value for axe_article.delete_flag
     *
     * @mbg.generated
     */
    public void setDeleteFlag(Short deleteFlag) {
        this.deleteFlag = deleteFlag;
    }
}