package com.senchuuhi.iweb.auto.entity;

import java.util.Date;

public class AxeConfig {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column axe_config.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column axe_config.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column axe_config.value
     *
     * @mbg.generated
     */
    private String value;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column axe_config.remark
     *
     * @mbg.generated
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column axe_config.version
     *
     * @mbg.generated
     */
    private String version;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column axe_config.vaild
     *
     * @mbg.generated
     */
    private String vaild;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column axe_config.creator
     *
     * @mbg.generated
     */
    private String creator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column axe_config.create_date
     *
     * @mbg.generated
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column axe_config.updater
     *
     * @mbg.generated
     */
    private String updater;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column axe_config.update_date
     *
     * @mbg.generated
     */
    private Date updateDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column axe_config.delete_flag
     *
     * @mbg.generated
     */
    private Short deleteFlag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column axe_config.id
     *
     * @return the value of axe_config.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column axe_config.id
     *
     * @param id the value for axe_config.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column axe_config.name
     *
     * @return the value of axe_config.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column axe_config.name
     *
     * @param name the value for axe_config.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column axe_config.value
     *
     * @return the value of axe_config.value
     *
     * @mbg.generated
     */
    public String getValue() {
        return value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column axe_config.value
     *
     * @param value the value for axe_config.value
     *
     * @mbg.generated
     */
    public void setValue(String value) {
        this.value = value == null ? null : value.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column axe_config.remark
     *
     * @return the value of axe_config.remark
     *
     * @mbg.generated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column axe_config.remark
     *
     * @param remark the value for axe_config.remark
     *
     * @mbg.generated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column axe_config.version
     *
     * @return the value of axe_config.version
     *
     * @mbg.generated
     */
    public String getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column axe_config.version
     *
     * @param version the value for axe_config.version
     *
     * @mbg.generated
     */
    public void setVersion(String version) {
        this.version = version == null ? null : version.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column axe_config.vaild
     *
     * @return the value of axe_config.vaild
     *
     * @mbg.generated
     */
    public String getVaild() {
        return vaild;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column axe_config.vaild
     *
     * @param vaild the value for axe_config.vaild
     *
     * @mbg.generated
     */
    public void setVaild(String vaild) {
        this.vaild = vaild == null ? null : vaild.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column axe_config.creator
     *
     * @return the value of axe_config.creator
     *
     * @mbg.generated
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column axe_config.creator
     *
     * @param creator the value for axe_config.creator
     *
     * @mbg.generated
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column axe_config.create_date
     *
     * @return the value of axe_config.create_date
     *
     * @mbg.generated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column axe_config.create_date
     *
     * @param createDate the value for axe_config.create_date
     *
     * @mbg.generated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column axe_config.updater
     *
     * @return the value of axe_config.updater
     *
     * @mbg.generated
     */
    public String getUpdater() {
        return updater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column axe_config.updater
     *
     * @param updater the value for axe_config.updater
     *
     * @mbg.generated
     */
    public void setUpdater(String updater) {
        this.updater = updater == null ? null : updater.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column axe_config.update_date
     *
     * @return the value of axe_config.update_date
     *
     * @mbg.generated
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column axe_config.update_date
     *
     * @param updateDate the value for axe_config.update_date
     *
     * @mbg.generated
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column axe_config.delete_flag
     *
     * @return the value of axe_config.delete_flag
     *
     * @mbg.generated
     */
    public Short getDeleteFlag() {
        return deleteFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column axe_config.delete_flag
     *
     * @param deleteFlag the value for axe_config.delete_flag
     *
     * @mbg.generated
     */
    public void setDeleteFlag(Short deleteFlag) {
        this.deleteFlag = deleteFlag;
    }
}