package com.senchuuhi.iweb.system.main.form;


import java.io.Serializable;
import java.util.Date;

public class ArticleForm implements Serializable {

    private static final long serialVersionUID = -8590999144781994606L;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column axe_article.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column axe_article.article_name
     *
     * @mbg.generated
     */
    private String articleName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column axe_article.article_author
     *
     * @mbg.generated
     */
    private String articleAuthor;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column axe_article.article_content
     *
     * @mbg.generated
     */
    private String articleContent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column axe_article.article_content
     *
     * @mbg.generated
     */
    private String articleDesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column axe_article.article_source
     *
     * @mbg.generated
     */
    private String articleSource;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column axe_article.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column axe_article.creator
     *
     * @mbg.generated
     */
    private String creator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column axe_article.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column axe_article.updater
     *
     * @mbg.generated
     */
    private String updater;

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getArticleName() {
        return articleName;
    }

    public void setArticleName(String articleName) {
        this.articleName = articleName;
    }

    public String getArticleAuthor() {
        return articleAuthor;
    }

    public void setArticleAuthor(String articleAuthor) {
        this.articleAuthor = articleAuthor;
    }

    public String getArticleContent() {
        return articleContent;
    }

    public void setArticleContent(String articleContent) {
        this.articleContent = articleContent;
    }

    public String getArticleDesc() {
        return articleDesc;
    }

    public void setArticleDesc(String articleDesc) {
        this.articleDesc = articleDesc;
    }

    public String getArticleSource() {
        return articleSource;
    }

    public void setArticleSource(String articleSource) {
        this.articleSource = articleSource;
    }

    public Date getCreateTime() {
        return createTime;
    }

    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    public String getCreator() {
        return creator;
    }

    public void setCreator(String creator) {
        this.creator = creator;
    }

    public Date getUpdateTime() {
        return updateTime;
    }

    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    public String getUpdater() {
        return updater;
    }

    public void setUpdater(String updater) {
        this.updater = updater;
    }
}
