package com.senchuuhi.iweb.auto.dao;

import com.senchuuhi.iweb.auto.entity.AxeArticle;
import com.senchuuhi.iweb.auto.entity.AxeArticleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AxeArticleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table axe_article
     *
     * @mbg.generated
     */
    long countByExample(AxeArticleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table axe_article
     *
     * @mbg.generated
     */
    int deleteByExample(AxeArticleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table axe_article
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table axe_article
     *
     * @mbg.generated
     */
    int insert(AxeArticle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table axe_article
     *
     * @mbg.generated
     */
    int insertSelective(AxeArticle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table axe_article
     *
     * @mbg.generated
     */
    List<AxeArticle> selectByExample(AxeArticleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table axe_article
     *
     * @mbg.generated
     */
    AxeArticle selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table axe_article
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") AxeArticle record, @Param("example") AxeArticleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table axe_article
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") AxeArticle record, @Param("example") AxeArticleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table axe_article
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(AxeArticle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table axe_article
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(AxeArticle record);
}