package com.senchuuhi.iweb.auto.dao;

import com.senchuuhi.iweb.auto.entity.AxeConfig;
import com.senchuuhi.iweb.auto.entity.AxeConfigExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AxeConfigMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table axe_config
     *
     * @mbg.generated
     */
    long countByExample(AxeConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table axe_config
     *
     * @mbg.generated
     */
    int deleteByExample(AxeConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table axe_config
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table axe_config
     *
     * @mbg.generated
     */
    int insert(AxeConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table axe_config
     *
     * @mbg.generated
     */
    int insertSelective(AxeConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table axe_config
     *
     * @mbg.generated
     */
    List<AxeConfig> selectByExample(AxeConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table axe_config
     *
     * @mbg.generated
     */
    AxeConfig selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table axe_config
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") AxeConfig record, @Param("example") AxeConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table axe_config
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") AxeConfig record, @Param("example") AxeConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table axe_config
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(AxeConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table axe_config
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(AxeConfig record);
}