package com.senchuuhi.iweb.auto.dao;

import com.senchuuhi.iweb.auto.entity.AxeUser;
import com.senchuuhi.iweb.auto.entity.AxeUserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AxeUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table axe_user
     *
     * @mbg.generated
     */
    long countByExample(AxeUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table axe_user
     *
     * @mbg.generated
     */
    int deleteByExample(AxeUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table axe_user
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table axe_user
     *
     * @mbg.generated
     */
    int insert(AxeUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table axe_user
     *
     * @mbg.generated
     */
    int insertSelective(AxeUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table axe_user
     *
     * @mbg.generated
     */
    List<AxeUser> selectByExample(AxeUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table axe_user
     *
     * @mbg.generated
     */
    AxeUser selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table axe_user
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") AxeUser record, @Param("example") AxeUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table axe_user
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") AxeUser record, @Param("example") AxeUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table axe_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(AxeUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table axe_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(AxeUser record);
}