package com.senchuuhi.iweb.auto.dao;

import com.senchuuhi.iweb.auto.entity.ResInfo;
import com.senchuuhi.iweb.auto.entity.ResInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ResInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table res_info
     *
     * @mbg.generated
     */
    long countByExample(ResInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table res_info
     *
     * @mbg.generated
     */
    int deleteByExample(ResInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table res_info
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table res_info
     *
     * @mbg.generated
     */
    int insert(ResInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table res_info
     *
     * @mbg.generated
     */
    int insertSelective(ResInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table res_info
     *
     * @mbg.generated
     */
    List<ResInfo> selectByExample(ResInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table res_info
     *
     * @mbg.generated
     */
    ResInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table res_info
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ResInfo record, @Param("example") ResInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table res_info
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ResInfo record, @Param("example") ResInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table res_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ResInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table res_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ResInfo record);
}